version: '3'
services:
  registry:
    # image: descartesresearch/teastore-registry
    image: teastore-registry
    expose:
      - "8080"
  db:
    # image: descartesresearch/teastore-db
    image: teastore-db
    expose:
      - "3306"
    ports:
      - "3306:3306"
  persistence:
    # image: descartesresearch/teastore-persistence
    image: teastore-persistence
    expose:
      - "8080"
    environment:
      HOST_NAME: "persistence"
      REGISTRY_HOST: "registry"
      DB_HOST: "db"
      DB_PORT: "3306"
  auth:
    # image: descartesresearch/teastore-auth
    image: teastore-auth
    expose:
      - "8080"
    environment:
      HOST_NAME: "auth"
      REGISTRY_HOST: "registry"
  image:
    # image: descartesresearch/teastore-image
    image: teastore-image
    expose:
      - "8080"
    environment:
      HOST_NAME: "image"
      REGISTRY_HOST: "registry"
  recommender:
    # image: descartesresearch/teastore-recommender
    image: teastore-recommender
    expose:
      - "8080"
    environment:
      HOST_NAME: "recommender"
      REGISTRY_HOST: "registry"
  webui:
    # image: descartesresearch/teastore-webui
    image: teastore-webui
    expose:
      - "8080"
      - "5005"
    environment:
      HOST_NAME: "webui"
      REGISTRY_HOST: "registry"
    ports:
      - "8080:8080"
      - "5005:5005"